config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :list_items
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "lists#index"

  resources :configurations, only: [] do
    get :ios_v1, on: :collection
  end
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list, dependent: :destroy
  acts_as_list scope: :list
  validates_presence_of :name


  after_save :check_list_completion

  private

  def check_list_completion
    list.update_completion_status!
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list
  before_action :set_list_item, only: %i[ show edit update destroy ]

  # GET /list_items or /list_items.json
  def index
    @list_items = @list.items
  end

  # GET /list_items/1 or /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
    @list = List.find(params[:list_id])
    @list_item = @list.list_items.find(params[:id])
  end

  # POST /list_items or /list_items.json
  def create
    @list_item = @list.list_items.build(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("todo-items", partial: "lists/todo_item", locals: { item: @list_item }),
            turbo_stream.replace("new_list_item_form", partial: "form", locals: { list: @list, list_item: @list.list_items.build })
          ]
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("new_list_item_form", partial: "form", locals: { list: @list, list_item: @list_item })
        end
      end
    end
  end

  # PATCH/PUT /list_items/1 or /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
      @list_item.list.update_completion_status!
       format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("todo-items", partial: "lists/todo_item", locals: { item: @list_item })
          ]
        end
      format.html { redirect_to @list_item.list, notice: "List Item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1 or /list_items/1.json
  def destroy
    @list_item.destroy!

    respond_to do |format|
      format.html { redirect_to list_path(@list), status: :see_other, notice: "List item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_list_item
      @list_item = @list.list_items.find(params[:id])
    end

    def list_item_params
      params.expect(list_item: [ :list_id, :name, :position, :completed ])
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= turbo_frame_tag "new_list_item_form", data: { turbo_frame: "_top" } do %>
  <%= form_with(model: [list, list_item], data: { action: "turbo:submit-end->form#reset" }) do |form| %>
    <% if list_item.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this List Item from being saved:</h2>

        <ul>
          <% list_item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, "Add To Do", style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit list_item.new_record? ? "Create List Item" : "Update List Item" %>
    </div>
  <% end %>
<% end %>

app/views/list_items/_list_item.html.erb
<div id="<%= dom_id list_item %>">
  <p>
    <strong>Name:</strong>
    <%= list_item.name %>
  </p>

  <p>
    <strong>List:</strong>
    <%= list_item.list_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= list_item.position %>
  </p>

  <p>
    <strong>Completed?:</strong>
    <%= list_item.completed %>
  </p>
  <hr>

</div>

app/views/list_items/create.turbo_stream.erb
<%= turbo_stream.append("todo-items", partial: "lists/todo_item", locals: { item: @list_item }) %>
<%= turbo_stream.replace(:new_list_item, partial: "form", locals: { list_item: @new_list_item }) %>  

app/views/list_items/edit.html.erb
<% content_for :title, "Editing list item" %>

<h1>Editing list item</h1>

<%= render 'form', list: @list, list_item: @list_item %>

<br>

app/views/list_items/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "List items" %>

<h1>List items</h1>

<div id="list_items">
  <% @list_items.each do |list_item| %>
    <%= render list_item %>
    <p>
      <%= link_to "Show this list item", list_item %>
    </p>
  <% end %>
</div>

<%= link_to "New list item", new_list_item_path %>

app/views/list_items/new.html.erb
<%= turbo_frame_tag :new_list_item do %>
  <%= render "form", list: @list, list_item: @list_item %>
<% end %>

app/views/list_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list_item %>

<div>
  <%= link_to "Edit this list item", edit_list_item_path(@list_item) %> |
  <%= link_to "Back to list items", list_items_path %>

  <%= button_to "Destroy this list item", @list_item, method: :delete %>
</div>

app/views/list_items/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@item), partial: "lists/todo_item", locals: { item: @item }) %>